default_agent: agent11
agents:
  agent10:
    name: agent10
    language: python
    node_version: '20'
    entrypoint: C:/Users/rsalvi.ext/GenAI assignment/New/agentcore_memory_runtime.py
    deployment_type: container
    runtime_type: null
    platform: linux/arm64
    container_runtime: none
    source_path: C:\Users\rsalvi.ext\GenAI assignment\New
    aws:
      execution_role: arn:aws:iam::684365645846:role/AmazonBedrockAgentCoreSDKRuntime-us-east-1-cfbc2a238d
      execution_role_auto_create: false
      account: '684365645846'
      region: us-east-1
      ecr_repository: 684365645846.dkr.ecr.us-east-1.amazonaws.com/bedrock-agentcore-agent10
      ecr_auto_create: false
      s3_path: null
      s3_auto_create: false
      network_configuration:
        network_mode: PUBLIC
        network_mode_config: null
      protocol_configuration:
        server_protocol: HTTP
      observability:
        enabled: true
      lifecycle_configuration:
        idle_runtime_session_timeout: null
        max_lifetime: null
    bedrock_agentcore:
      agent_id: agent10-J0ceb35mDa
      agent_arn: arn:aws:bedrock-agentcore:us-east-1:684365645846:runtime/agent10-J0ceb35mDa
      agent_session_id: training-session-00000000000000001
    codebuild:
      project_name: bedrock-agentcore-agent10-builder
      execution_role: arn:aws:iam::684365645846:role/AmazonBedrockAgentCoreSDKCodeBuild-us-east-1-cfbc2a238d
      source_bucket: bedrock-agentcore-codebuild-sources-684365645846-us-east-1
    memory:
      mode: STM_AND_LTM
      memory_id: memory_taxim-7CBpMUGkSX
      memory_arn: null
      memory_name: agent10_memory
      event_expiry_days: 30
      first_invoke_memory_check_done: false
      was_created_by_toolkit: false
    identity:
      credential_providers: []
      workload: null
    aws_jwt:
      enabled: false
      audiences: []
      signing_algorithm: ES384
      issuer_url: null
      duration_seconds: 300
    authorizer_configuration: null
    request_header_configuration: null
    oauth_configuration: null
    api_key_env_var_name: null
    api_key_credential_provider_name: null
    is_generated_by_agentcore_create: false
  agent11:
    name: agent11
    language: python
    node_version: '20'
    entrypoint: C:/Users/rsalvi.ext/GenAI assignment/New/agentcore_memory_runtime.py
    deployment_type: container
    runtime_type: null
    platform: linux/arm64
    container_runtime: none
    source_path: C:\Users\rsalvi.ext\GenAI assignment\New
    aws:
      execution_role: arn:aws:iam::684365645846:role/AmazonBedrockAgentCoreSDKRuntime-us-east-1-9505dfcdfb
      execution_role_auto_create: false
      account: '684365645846'
      region: us-east-1
      ecr_repository: 684365645846.dkr.ecr.us-east-1.amazonaws.com/bedrock-agentcore-agent11
      ecr_auto_create: false
      s3_path: null
      s3_auto_create: false
      network_configuration:
        network_mode: PUBLIC
        network_mode_config: null
      protocol_configuration:
        server_protocol: HTTP
      observability:
        enabled: true
      lifecycle_configuration:
        idle_runtime_session_timeout: null
        max_lifetime: null
    bedrock_agentcore:
      agent_id: agent11-094Ifx81Gj
      agent_arn: arn:aws:bedrock-agentcore:us-east-1:684365645846:runtime/agent11-094Ifx81Gj
      agent_session_id: training-session-00000000000000001
    codebuild:
      project_name: bedrock-agentcore-agent11-builder
      execution_role: arn:aws:iam::684365645846:role/AmazonBedrockAgentCoreSDKCodeBuild-us-east-1-9505dfcdfb
      source_bucket: bedrock-agentcore-codebuild-sources-684365645846-us-east-1
    memory:
      mode: STM_AND_LTM
      memory_id: memory_taxim-7CBpMUGkSX
      memory_arn: null
      memory_name: agent11_memory
      event_expiry_days: 30
      first_invoke_memory_check_done: false
      was_created_by_toolkit: false
    identity:
      credential_providers: []
      workload: null
    aws_jwt:
      enabled: false
      audiences: []
      signing_algorithm: ES384
      issuer_url: null
      duration_seconds: 300
    authorizer_configuration: null
    request_header_configuration: null
    oauth_configuration: null
    api_key_env_var_name: null
    api_key_credential_provider_name: null
    is_generated_by_agentcore_create: false
