default_agent: Agent12
agents:
  Agent12:
    name: Agent12
    language: python
    node_version: '20'
    entrypoint: C:/Users/rsalvi.ext/GenAI assignment/Assignment 4/multi_agent_runtime.py
    deployment_type: container
    runtime_type: null
    platform: linux/arm64
    container_runtime: none
    source_path: C:\Users\rsalvi.ext\GenAI assignment\Assignment 4
    aws:
      execution_role: arn:aws:iam::684365645846:role/AmazonBedrockAgentCoreSDKRuntime-us-east-1-e537ec3ca6
      execution_role_auto_create: false
      account: '684365645846'
      region: us-east-1
      ecr_repository: 684365645846.dkr.ecr.us-east-1.amazonaws.com/bedrock-agentcore-agent12
      ecr_auto_create: false
      s3_path: null
      s3_auto_create: false
      network_configuration:
        network_mode: PUBLIC
        network_mode_config: null
      protocol_configuration:
        server_protocol: HTTP
      observability:
        enabled: true
      lifecycle_configuration:
        idle_runtime_session_timeout: null
        max_lifetime: null
    bedrock_agentcore:
      agent_id: Agent12-E2sfAd6Iyy
      agent_arn: arn:aws:bedrock-agentcore:us-east-1:684365645846:runtime/Agent12-E2sfAd6Iyy
      agent_session_id: c6a9c025-0cb9-41e5-991a-9bfafc671842
    codebuild:
      project_name: bedrock-agentcore-agent12-builder
      execution_role: arn:aws:iam::684365645846:role/AmazonBedrockAgentCoreSDKCodeBuild-us-east-1-e537ec3ca6
      source_bucket: bedrock-agentcore-codebuild-sources-684365645846-us-east-1
    memory:
      mode: NO_MEMORY
      memory_id: null
      memory_arn: null
      memory_name: null
      event_expiry_days: 30
      first_invoke_memory_check_done: false
      was_created_by_toolkit: false
    identity:
      credential_providers: []
      workload: null
    aws_jwt:
      enabled: false
      audiences: []
      signing_algorithm: ES384
      issuer_url: null
      duration_seconds: 300
    authorizer_configuration: null
    request_header_configuration: null
    oauth_configuration: null
    api_key_env_var_name: null
    api_key_credential_provider_name: null
    is_generated_by_agentcore_create: false
